### ISSUE TITLE
Auto completion doesn't work after dot

### ISSUE THREAD

**Issue by mahdi739** [blorbb/leptos-mview#13]
When we write a dot, the R-A doesn't show auto completion and we have to type at least one more character after dot to make auto completion work.

Here is the comparison between two situations:

**Dot following with a character:**
```
p;
p{{
  let r=12i32;
  r.g            
 }}
```

```rust
{
  #[allow(unused_braces)]
  ::leptos::Fragment::lazy(|| {
    (<[_]>::into_vec(
      #[rustc_box]
      $crate::boxed::Box::new([
        (::leptos::IntoView::into_view(::leptos::html::p())),
        (::leptos::IntoView::into_view(::leptos::html::p().child({
          let r = 12i32;
          r.g
        }))),
      ]),
    ))
  })
}
```
**Only dot:**
```
p;
p{{
  let r=12i32;
  r.            
 }}
```

```rust
{
  #[allow(unused_braces)]
  ::leptos::Fragment::lazy(|| {
    (<[_]>::into_vec(
      #[rustc_box]
      $crate::boxed::Box::new([]),
    ))
  })
}
```

**Comment by blorbb** [comment]
Thanks for the repro! I think I noticed this before too but couldn't figure out why it didn't work.
I think it may be because I'm expanding fragments into `::std::vec![...]`, and partial expressions are expanded in there properly, but `vec![]` matches on full expressions, so it doesn't manage to expand the partial expression.

I'll make a fix soon. Thanks again for the repro, should be a relatively simple fix!
